[package]
name = "sider"
description = "A Multithreaded Redis clone written from scratch in Rust."
license = "MIT"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
